/*
ROT Developers and Contributors:
Moises (OWNER/CEO/Developer),
Aex66 (Developer),
notbeer (ROT's base code)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
__________ ___________________
\______   \\_____  \__    ___/
 |       _/ /   |   \|    |
 |    |   \/    |    \    |
 |____|_  /\_______  /____|
        \/         \/
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
© Copyright 2022 all rights reserved by Mo9ses. Do NOT steal, copy the code, or claim it as yours!
Please message Mo9ses#8583 on Discord, or join the ROT discord: https://discord.com/invite/2ADBWfcC6S
Website: https://www.rotmc.ml
Docs: https://docs.google.com/document/d/1hasFU7_6VOBfjXrQ7BE_mTzwacOQs5HC21MJNaraVgg
Thank you!
*/
import { DatabasePaper } from '../../Papers/DatabasePaper.js';
import Server from '../../ServerBook.js';
import config from '../../config.js';
Server.command.register({
    cancelMessage: true,
    name: 'rottle',
    description: 'A fun little word game were you have to guess the word that ROT is thinking of :)',
    aliases: ['rm', 'rottie'],
    category: 'Fantasy',
    documentation: {
        usage: 'rm <play|try|quit> <word>',
        information: 'This game will make you guess a random word ROT chooses. There are only 300 words so after a while you might know them all, so I will refresh them every update or two.',
        examples: [
            'rottle play',
            'rottle try home',
            'rm try ice',
            'rottle try good',
            'rottie quit',
            'rm stats'
        ],
        developers: ['Mo9ses']
    }
}, (chatmsg, args) => {
    const rottle = new DatabasePaper('rottle'), play = ['play', 'fun', 'p', 'py', 'start', 's'], tryo = ['try', 'tryo', 'do', 'maybe', 'this', 't', 'tr'], quit = ['quit', 'no', 'ah', 'ahh', 'again', 'another', 'hate', 'q', 'qu'], stats = ['stats', 's', 'info', 'sto'];
    if (!rottle.has(chatmsg.sender.name))
        rottle.set(chatmsg.sender.name, { inMatch: false });
    if (play.includes(args[0])) {
        if (rottle.get(chatmsg.sender.name).inMatch)
            return Server.eBroadcast('You cannot start a game with me if you are already in a game with me! Type "§4!rm quit§c" in chat and give me the win loser', chatmsg.sender.name, 'ROTLE');
        rottle.set(chatmsg.sender.name, Object.assign(rottle.get(chatmsg.sender.name), {
            inMatch: true,
            word: words[~~(Math.random() * words.length)],
            attempts: 0,
            matchesPlayed: (rottle.get(chatmsg.sender.name)?.matchesPlayed ?? 0) + 1
        }));
        return Server.broadcast(`The match has started! The word I am thinking of is §c${rottle.get(chatmsg.sender.name).word.length}§7 letters long! You only get §c${config.rottleAttemps}§7 attempts!`, chatmsg.sender.name, 'ROT');
    }
    if (tryo.includes(args[0])) {
        if (!rottle.get(chatmsg.sender.name).inMatch)
            return Server.eBroadcast('You are not in a match with me yet... Type "§4!rm play§c" in chat to start one.', chatmsg.sender.name, 'ROTLE');
        if (args[1].replace(/[a-z]/g, '') !== '' || args[2])
            return Server.eBroadcast('It\'s only one word, and the word doesn\'t have any numbers or stuff like that. Don\'t worry, I didn\'t count that as a "attempt"', chatmsg.sender.name, 'ROT');
        rottle.set(chatmsg.sender.name, Object.assign(rottle.get(chatmsg.sender.name), { attempts: rottle.get(chatmsg.sender.name).attempts + 1 }));
        if (rottle.get(chatmsg.sender.name).word === args[1]) {
            rottle.set(chatmsg.sender.name, Object.assign(rottle.get(chatmsg.sender.name), {
                inMatch: false,
                wins: (rottle.get(chatmsg.sender.name)?.wins ?? 0) + 1,
                averageAttempts: (rottle.get(chatmsg.sender.name)?.averageAttempts ?? 0) + rottle.get(chatmsg.sender.name).attempts
            }));
            return Server.broadcast(`Dang, you actally got the word right... GG\n§aWord:§c ${rottle.get(chatmsg.sender.name).word}\n§aAttempts:§c ` + rottle.get(chatmsg.sender.name).attempts, chatmsg.sender.name, 'ROT');
        }
        if (rottle.get(chatmsg.sender.name).attempts >= config.rottleAttemps) {
            rottle.set(chatmsg.sender.name, Object.assign(rottle.get(chatmsg.sender.name), {
                inMatch: false,
                losses: (rottle.get(chatmsg.sender.name)?.losses ?? 0) + 1
            }));
            if (config.rottleRewards)
                Server.runCommands(config.rottleRewardsCmds.map(cmd => { return cmd.replace('@rottler', `"${chatmsg.sender.name}"`); }));
            return Server.broadcast(`§cTen strikes, your OUT!§7 Thanks for the free win! The word was §c${rottle.get(chatmsg.sender.name).word}§7 by the way XD.`, chatmsg.sender.name, 'ROT');
        }
        let tryWord = args[1].split('').map(letter => {
            return rottle.get(chatmsg.sender.name).word.split('').includes(letter) ? `§a${letter}` : `§4${letter}`;
        });
        return Server.broadcast(`§cWrong!§7 Here are the letters that are in that word: §l${tryWord.join('')}§r§7. You have §c${10 - rottle.get(chatmsg.sender.name).attempts}§7 attempts left!`, chatmsg.sender.name, 'ROT');
    }
    if (quit.includes(args[0])) {
        if (!rottle.get(chatmsg.sender.name).inMatch)
            return Server.eBroadcast('You are not in a match with me yet... Type "§4!rm play§c" in chat to start one.', chatmsg.sender.name, 'ROTLE');
        rottle.set(chatmsg.sender.name, Object.assign(rottle.get(chatmsg.sender.name), {
            inMatch: false,
            losses: (rottle.get(chatmsg.sender.name)?.losses ?? 0) + 1
        }));
        return Server.broadcast('Thanks for the free win loser!', chatmsg.sender.name, 'ROT');
    }
    if (stats.includes(args[0]))
        return Server.broadcast(`Here are your stats:\n§aWins:§c ${rottle.get(chatmsg.sender.name)?.wins ?? 0}\n§aLosses:§c ${rottle.get(chatmsg.sender.name)?.losses ?? '0?!?! Impossible!'}\n§aWin-loss ratio:§c ${(rottle.get(chatmsg.sender.name)?.wins / rottle.get(chatmsg.sender.name)?.losses)}\n§aMatches played:§c ${rottle.get(chatmsg.sender.name)?.matchesPlayed ?? 0}\n§aAverage attemps before a win:§c ` + (rottle.get(chatmsg.sender.name)?.averageAttempts / rottle.get(chatmsg.sender.name)?.wins), chatmsg.sender.name, 'ROTTLE');
    Server.eBroadcast(Server.lang.error2, chatmsg.sender.name, 'ROTTLE');
});
//I wrote these words myself becase every other word list on the internet is bit too difficult for the average Minecraft player
const words = [
    'cattle',
    'resident',
    'situation',
    'lace',
    'check',
    'share',
    'reliance',
    'learn',
    'drink',
    'north',
    'document',
    'extension',
    'elapse',
    'familiar',
    'worker',
    'ladder',
    'provision',
    'dentist',
    'throat',
    'knee',
    'host',
    'institution',
    'war',
    'discover',
    'pavement',
    'character',
    'slump',
    'pudding',
    'notice',
    'predict',
    'conductor',
    'blind',
    'hip',
    'rabbit',
    'respect',
    'so',
    'explode',
    'trance',
    'bold',
    'address',
    'guitar',
    'execute',
    'reform',
    'peasant',
    'faith',
    'walk',
    'church',
    'gravity',
    'form',
    'candle',
    'flavor',
    'introduction',
    'flood',
    'cheek',
    'eat',
    'fur',
    'budge',
    'preach',
    'direction',
    'kidney',
    'folklore',
    'trunk',
    'colony',
    'banquet',
    'restless',
    'diet',
    'urine',
    'vehicle',
    'profession',
    'fiction',
    'prize',
    'friend',
    'clinic',
    'seat',
    'revive',
    'harm',
    'coerce',
    'tender',
    'pause',
    'concentrate',
    'tidy',
    'sip',
    'profile',
    'cigarette',
    'nursery',
    'dictionary',
    'useful',
    'ward',
    'language',
    'clue',
    'us',
    'exclusive',
    'swipe',
    'part',
    'grimace',
    'hunter',
    'accurate',
    'constitution',
    'blackmail',
    'retreat',
    'outfit',
    'priority',
    'inspiration',
    'forum',
    'bracket',
    'willpower',
    'win',
    'atmosphere',
    'way',
    'minor',
    'acquaintance',
    'hall',
    'waiter',
    'right',
    'wording',
    'accompany',
    'tourist',
    'feeling',
    'program',
    'mercy',
    'prescription',
    'ear',
    'suspicion',
    'rate',
    'temple',
    'rhetoric',
    'philosophy',
    'fan',
    'video',
    'speed',
    'discovery',
    'sandwich',
    'carpet',
    'patience',
    'repetition',
    'contrast',
    'daughter',
    'condition',
    'worry',
    'ball',
    'tin',
    'system',
    'movement',
    'sweat',
    'ample',
    'function',
    'owe',
    'finish',
    'nut',
    'ballet',
    'rainbow',
    'score',
    'maze',
    'plug',
    'achieve',
    'swear',
    'list',
    'layout',
    'dependence',
    'link',
    'cylinder',
    'artist',
    'read',
    'garage',
    'deserve',
    'runner',
    'fresh',
    'joke',
    'term',
    'recording',
    'agency',
    'code',
    'cultural',
    'snatch',
    'welcome',
    'order',
    'magnetic',
    'dough',
    'active',
    'hostility',
    'architect',
    'climate',
    'interactive',
    'fair',
    'feeling',
    'lung',
    'aisle',
    'patient',
    'center',
    'elbow',
    'refrigerator',
    'handy',
    'defend',
    'poem',
    'reject',
    'embarrassment',
    'courtesy',
    'am',
    'literature',
    'lighter',
    'garage',
    'recovery',
    'fraud',
    'belly',
    'secure',
    'gaffe',
    'film',
    'embrace',
    'hardware',
    'package',
    'broadcast',
    'drain',
    'fashionable',
    'wrestle',
    'prisoner',
    'layer',
    'building',
    'watch',
    'video',
    'duke',
    'bridge',
    'nose',
    'curriculum',
    'confidence',
    'resort',
    'ecstasy',
    'economics',
    'valley',
    'exchange',
    'baseball',
    'patent',
    'industry',
    'tongue',
    'rhythm',
    'elegant',
    'enlarge',
    'express',
    'single',
    'flourish',
    'photography',
    'pollution',
    'judge',
    'give',
    'banish',
    'directory',
    'displace',
    'persist',
    'president',
    'disappoint',
    'understand',
    'humor',
    'revenge',
    'fossil',
    'thick',
    'ancestor',
    'mutation',
    'confrontation',
    'height',
    'love',
    'chaos',
    'parameter',
    'article',
    'exact',
    'half',
    'suitcase',
    'hilarious',
    'sunshine',
    'bird',
    'identity',
    'egg',
    'prospect',
    'similar',
    'favor',
    'participate',
    'union',
    'identification',
    'tradition',
    'common',
    'property',
    'addicted',
    'professional',
    'increase',
    'cope',
    'disappointment',
    'sell',
    'hole',
    'beginning',
    'film',
    'struggle',
    'bedroom',
    'cover',
    'chain',
    'implication',
    'corner',
    'drift',
    'equation',
    'provincial',
    'flawed',
    'disagree',
    'team',
];
